name: Pact Contract Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  consumer:
    runs-on: ubuntu-latest
    env:
      PACTFLOW_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
      GIT_COMMIT: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run consumer tests
        run: npm run test:pact:consumer

  provider:
    needs: consumer
    runs-on: ubuntu-latest
    env:
      PACTFLOW_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
      GIT_COMMIT: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run provider verification
        run: npm run test:pact:provider

  can-i-deploy:
    needs: [consumer, provider]
    runs-on: ubuntu-latest
    env:
      PACTFLOW_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
    
    steps:
      - name: Install Pact CLI
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-linux-x86_64.tar.gz
          tar xzf pact-1.91.0-linux-x86_64.tar.gz
          
      - name: Check if deployment is possible
        run: |
          ./pact/bin/pact-broker can-i-deploy \
            --broker-base-url=https://org-a-849e.pactflow.io \
            --broker-token=$PACTFLOW_TOKEN \
            --pacticipant=BookService \
            --version=${{ github.sha }} \
            --to-environment=production 