name: Deploy and Record

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy-and-record:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: z1/z1
    env:
      PACTFLOW_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Pact CLI
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-linux-x86_64.tar.gz
          tar xzf pact-1.91.0-linux-x86_64.tar.gz
      
      # Your actual deployment steps would go here
      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
      
      - name: Record deployment in PactFlow
        run: |
          ./pact/bin/pact-broker record-deployment \
            --broker-base-url=https://org-a-849e.pactflow.io \
            --broker-token=$PACTFLOW_TOKEN \
            --pacticipant=BookService \
            --version=${{ github.sha }} \
            --environment=${{ github.event.inputs.environment }} 